// src/lib/components/site-footer.svelte
<script lang="ts">
	import { siteConfig } from '$lib/config';
	import Github from '@lucide/svelte/icons/github';
	import Linkedin from '@lucide/svelte/icons/linkedin';
	import { buttonVariants } from './ui/button';

	const links = Object.keys(siteConfig.links)
		.map((key) => ({
			name: key,
			url: siteConfig.links[key as keyof typeof siteConfig.links].replace(/\/+$/, ''),
			Icon: key === 'github' ? Github : key === 'linkedin' ? Linkedin : null
		}))
		.filter((link) => link.name !== 'x');
</script>

<footer class="w-full border border-t-primary bg-background pt-5 pb-10">
	<div class="flex h-full w-full flex-col items-center justify-center gap-2">
		<div class="flex gap-1">
			{#each links as link (link.name)}
				<a
					aria-label={`Visit ${siteConfig.name}'s ${link.name} profile`}
					href={link.url}
					target="_blank"
					rel="external noopener noreferrer"
					class={buttonVariants({ size: 'icon', variant: 'ghost' })}
				>
					{#if link.Icon}
						<link.Icon aria-hidden="true" />
					{:else}
						{link.name}
					{/if}
				</a>
			{/each}
		</div>
		<p class="text-xl leading-[1.1] font-bold">
			{siteConfig.name}
			{new Date().getFullYear()}.
		</p>
	</div>
</footer>

// src/components/layouts/site-footer.tsx
import { cn } from "@/lib/utils"
import Link from "next/link"
import { Icons } from "../icons"
import { buttonVariants } from "../ui/button"

interface LinkItem {
  href: string
  icon: keyof typeof Icons
}

const links: LinkItem[] = [
  { href: "https://www.facebook.com/brix.porras/", icon: "facebook" },
  {
    href: "https://www.linkedin.com/in/brixter-porras-7bbaa91bb/",
    icon: "linked",
  },
  { href: "https://github.com/Brix101/", icon: "github" },
]

function Footer() {
  return (
    <footer className="w-full border border-t-primary bg-background pb-10 pt-5">
      <div className="flex h-full w-full flex-col items-center justify-center gap-2">
        <div className="flex gap-1">
          {links.map((link, index) => {
            const Icon = Icons[link.icon]
            return (
              <Link
                key={index}
                href={link.href}
                target="_blank"
                className={cn(
                  buttonVariants({
                    size: "icon",
                  }),
                  "h-6 w-6 p-1",
                )}
              >
                <Icon aria-hidden="true" />{" "}
              </Link>
            )
          })}
        </div>
        <div>
          <p className="text-xl font-bold leading-[1.1]">
            Brixter Porras {new Date().getFullYear()}.
          </p>
        </div>
      </div>
    </footer>
  )
}

export default Footer
