// src/components/layouts/main-nav.tsx
"use client";

import Link from "next/link";

import { siteConfig } from "@/config/site";
import { cn, handleScroll } from "@/lib/utils";

import { Icons } from "@/components/icons";
import { buttonVariants } from "@/components/ui/button";
import { navButtons } from "@/config/docs";

interface Props {
  isOffset?: boolean;
  activeSection: string | null;
}

export function MainNav({ isOffset, activeSection }: Props) {
  const secNavButtons = navButtons.map((item, index) => {
    const isActive = item.sectionId === activeSection;
    if (item.isHidden) {
      return;
    }

    return (
      <Link
        key={index}
        className={cn(
          "bg-background uppercase outline outline-1 outline-primary disabled:bg-primary disabled:text-background disabled:text-opacity-100",
          buttonVariants({
            variant: isActive ? "default" : "ghost",
            size: "sm",
          }),
        )}
        href={"#" + item.sectionId}
        onClick={handleScroll}
      >
        {item.label}
      </Link>
    );
  });

  return (
    <div className="hidden w-full items-center justify-between md:flex">
      <div>
        <Link
          className={cn(
            "flex items-center space-x-2",
            !isOffset ? "hidden" : "visible",
          )}
          href="#section-hero"
          onClick={handleScroll}
        >
          <Icons.mainLogo className={cn("h-10 w-10")} />
          <span className="hidden break-normal font-bold sm:inline-block">
            {siteConfig.name}
          </span>
        </Link>
      </div>
      <div className="space-x-2">{secNavButtons}</div>
    </div>
  );
}

// src/lib/components/main-nav.svelte
<script lang="ts">
	import { siteConfig, siteLinks } from '$lib/config';
	import { cn, handleScroll } from '$lib/utils.js';
	import type { HTMLAttributes } from 'svelte/elements';
	import BrixLogo from './brix-logo.svelte';
	import { buttonVariants } from './ui/button';

	let {
		isOffset = false,
		class: className,
		...restProps
	}: {
		class?: string;
		isOffset?: boolean;
	} & HTMLAttributes<HTMLElement> = $props();
</script>

<nav class={cn('items-center justify-between', className)} {...restProps}>
	<div class="pr-2">
		<a
			href="#section-hero"
			class={cn('group flex items-center space-x-2', isOffset ? 'visible' : 'hidden')}
			aria-label="Go to Hero section"
			onclick={handleScroll}
		>
			<BrixLogo class="h-6 w-6" />
			<p class="hidden font-bold break-normal group-hover:text-primary sm:inline-block">
				{siteConfig.name}
			</p>
		</a>
	</div>
	<div class="space-x-2">
		{#each siteLinks as link}
			<a
				href={link.href}
				class={buttonVariants({ variant: 'ghost', size: 'sm' })}
				onclick={link.isSection ? handleScroll : undefined}
			>
				{link.name}
			</a>
		{/each}
	</div>
</nav>
