// src/components/layouts/site-header.tsx
"use client";

import { ModeToggle } from "@/components/mode-toggle";
import useActiveSection from "@/hooks/useActiveSection";
import useScrollOffset from "@/hooks/useScrollOffset";
import { cn } from "@/lib/utils";
import { MainNav } from "./main-nav";
import { MobileNav } from "./mobile-nav";

function SiteHeader() {
  const isOffset = useScrollOffset(20);
  const activeSection = useActiveSection();

  return (
    <header className="pointer-events-none fixed top-0 z-50 w-full">
      <div className="container">
        <div
          className={cn(
            "flex items-center space-x-2 rounded-xl border px-8 py-4 transition-all",
            isOffset
              ? "mt-2 border-primary bg-background/95 backdrop-blur-sm"
              : "border-transparent",
          )}
        >
          <MainNav isOffset={isOffset} activeSection={activeSection} />
          <MobileNav isOffset={isOffset} activeSection={activeSection} />
          <div className="pointer-events-auto flex flex-1 items-center justify-between md:justify-end ">
            <ModeToggle />
          </div>
        </div>
      </div>
    </header>
  );
}

export default SiteHeader;

// src/lib/components/site-header.svelte
<script lang="ts">
	import { cn } from '$lib/utils';
	import { onMount } from 'svelte';
	import MainNav from './main-nav.svelte';
	import ModeSwitcher from './mode-switcher.svelte';

	let isOffset = false;

	function handleScroll() {
		isOffset = window.scrollY > 20;
	}

	onMount(() => {
		window.addEventListener('scroll', handleScroll);

		handleScroll();

		return () => window.removeEventListener('scroll', handleScroll);
	});
</script>

<header class="site-header fixed top-0 z-50 w-full">
	<div
		class={cn(
			'mx-auto flex items-center justify-between border-b p-4 transition-all md:container md:rounded-xl md:border md:px-8 md:py-4',
			isOffset ? 'border-primary bg-background/85 backdrop-blur-md md:mt-2' : 'border-transparent'
		)}
	>
		<div class="pointer-events-auto w-full">
			<MainNav class="hidden md:flex" {isOffset} />
		</div>
		<div class="pointer-events-auto pl-2">
			<ModeSwitcher />
		</div>
	</div>
</header>
